global:
  scrape_interval: 60s
  external_labels:
    monitor: 'codelab-monitor'
      
scrape_configs:

  - job_name: 'vllm'
    scrape_interval: 5s
    static_configs:
      - targets: ['vllm:8000']

  - job_name: 'gpu'
    scrape_interval: 15s
    static_configs:
      - targets: ['gpu-stats:9400']
